import { Audiowide } from "next/font/google";
import "./globals.css";

const audioWide = Audiowide({
  variable: "--font-audiowide",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Rise to Top 1%",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={audioWide.className} // Applying the Audiowide font globally
      >
        {children}
      </body>
    </html>
  );
}
